import Descriptions from "@/components/Descriptions";
import Dog from "@/components/Dog";
import Parent from "@/components/Parent";
import User from "@/components/User";
import Welcome from "@/components/Welcome";
import Head from "next/head";

export default function Home() {
  return (
    <> {/* fragment -> funciona como um elemento pai  */}
      <Head>
        <title>Fundamentos do React</title>
        <meta name="description" content="Generated by create next app" />
        <meta name="viewport" content="width=device-width, initial-scale=1" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <div className="">
        Hello World
        {/* chamando o componente */}
        <Welcome/>
        {/* Importando o componente com expressao jsx */}
        <User name={"Arthur"}/>
        {/* Componente que posui um filho incorporado */}
        <Parent/>
        {/* Componente que usa props para variaveis */}
        <Descriptions name={"Arthur"} age={18} />
        {/* Desestruturação para passar props */}
        <Dog name="Buck" breed="Border Collie" />
      </div>
        
    </>
  );
}
